# Generated by Django 5.2.6 on 2025-09-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instacaio', '0002_alter_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
